name: builds

on:
  push:
    branches: [develop, main]
    tags:
      - "v\\d+\\.\\d+\\.\\d+[ab]?"
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: yezz123/setup-uv@v4
      - name: Run unit tests
        run: uv run pytest
      - name: Build Python package
        if: startsWith(github.ref, 'refs/tags/')
        run: uv build
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        run: uv publish
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
