name: PR checks

on:
  pull_request:
    branches: [develop, main]
    paths-ignore:
      - .github/workflows/**

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: yezz123/setup-uv@v4
      - name: Run unit tests
        run: uv run pytest
      - name: Build Python package
        run: uv build
