name: Trigger release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Bump type
        required: true
        type: choice
        options: [patch, minor, major]

permissions:
  contents: write

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ssh-key: ${{ secrets.AUTOCOMMITS_DEPLOY_KEY }} 
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.14.4"
      - uses: yezz123/setup-uv@4819cd88f8d0991d99e4d10c85da3e4d22528951 # v4
      - run: uv run bumpver update --${{ inputs.bump }}
      - name: Get new version
        id: pyproject
        uses: maybe-hello-world/pyproject-check-version@cb964e82b3c8a0b1cedb117da63e1761c46600b8 # v4
      - name: Update changelog
        if: steps.pyproject.outputs.local_version_is_higher == 'true'
        run: uv run keepachangelog release ${{  steps.pyproject.outputs.local_version }}
      - name: Debug changes
        run: |
          git status
          echo New version: ${{ steps.pyproject.outputs.local_version }}
          echo Changes:
          git diff
      - name: Commit and tag changes
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        if: steps.pyproject.outputs.local_version_is_higher == 'true'
        with:
          message: "🔖 Release ${{ steps.pyproject.outputs.local_version }}"
          tag: v${{ steps.pyproject.outputs.local_version }}

